module.exports = {
  SUCCESS: "Success",
  NOTFOUND: "Not Found",
  UNAUTHORIZED: "Unauthorized",
  BAD_REQUEST: "Bad Request",
  IDREQUIRED: "id is required ",
  ADMIN_ALLOWED: [
    "get-store",
    "store",
    "customer",
    "employee",
    "users",
    "fileUpload",
    "receiptDetails",
    "updateInspection",
    "getTemplates",
    "getTemplate",
    "getFields",
    "addClient",
    "updateClient",
    "getClients",
    "getClient",
    "deleteClient",
    "deleteUser",
    "getSurveys",
    "getSurvey",
    "addSurvey",
    "deleteUser",
    "deleteLookup",
    "updateUser",
    "assignSurvey",
    "bulkUpload",
    "deleteSurvey",
    "getUsers",
    "getSurveyors",
    "publishSurvey",
    "updateSurvey",
  ],
  SURVEYOR_ALLOWED: [
    "fileUpload",
    "getLookup",
    "getFields",
    "addLookup",
    "getTemplate",
    "getClients",
    "getSurvey",
    "submitSurvey",
    "updateInspection",
    "mySurveys",
  ],
};
